apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tu9uv2n9g-nodejs
  janus-idp.io/tekton: tu9uv2n9g-nodejs
  backstage.io/kubernetes-id: tu9uv2n9g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tu9uv2n9g-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
